version: '3'
services:
  partic-frontend:
    container_name: partic-frontend
    image: partic-frontend
    ports:
      - '2023:2023'  
    networks:
      - partic
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:2024
      - REACT_APP_FRONTEND_URL=http://partic.zfserver.local
      - PORT=2023
      - REACT_APP_HOURLY_RATE=5.00
      - TIMEZONE=America/Phoenix

  partic-backend:
    container_name: partic-backend
    image: partic-backend
    ports:
      - '2024:2024'  
    networks:
      - partic
    environment:
      - DB_HOST=partic-db
      - DB_USER=admin
      - DB_PASSWORD=parkingTheBus123
      - DB_DATABASE=partic
      - JWT_SECRET=TV4fUqPU5Z
      - PORT=2024
      - REACT_APP_HOURLY_RATE=5
    depends_on:
      - partic-db

  partic-db:
    container_name: partic-db
    image: partic-db
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - partic

networks:
  partic:
    external: true
    ipam:
      driver: default

volumes:
  db-data:
